ls:
  # 모든 폴더는 kebab-case
  .dir: kebabcase

  # 기본 파일 규칙 (camelCase)
  .js: camelcase
  .mdx: kebabcase
  .ts: camelcase

  # React 컴포넌트는 PascalCase
  packages/icons:
    .dir: kebabcase
    .tsx: PascalCase

  packages/ui:
    .dir: kebabcase
    .tsx: PascalCase

ignore:
  - .changeset
  - .git
  - .github
  - .husky
  - .storybook
  - '**/.storybook'
  - .turbo
  - '**/.turbo'
  - .vscode
  - build
  - coverage
  - dist
  - node_modules
  - '**/node_modules'
  - storybook-static
  - '**/storybook-static'
